#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format && npm run lint:check && forge test --fork-url "https://lb.drpc.org/ogrpc?network=arbitrum&dkey=AndBdVMW9kqLhpV95Kl_zsdLWrYu3PsR7qO5GtyyLTIM"
